name: "Flipt Lint"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.FLIPT_BOT_APP_ID }}
          private_key: ${{ secrets.FLIPT_BOT_PRIVATE_KEY_PEM }}
          installation_id: ${{ secrets.FLIPT_BOT_FFS_INSTALLATION_ID }}

      - uses: actions/checkout@v3
        with:
          path: ./apps

      - uses: actions/checkout@v3
        with:
          repository: flipt-io/ffs
          path: ./ffs
          token: ${{ steps.generate_token.outputs.token }}
          ref: gm/fix-go-rule-flag-key-match

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ffs/target/
          key: ${{ runner.os }}-cargo-${{ hashfiles('/ffs/Cargo.lock') }}

      - name: Build FFS
        run: cargo build
        working-directory: ./ffs

      - name: Update Path
        run: echo "$PWD/ffs/target/debug" >> $GITHUB_PATH

      - name: Set Workspace
        run: echo "GITHUB_WORKSPACE=$PWD/apps" >> $GITHUB_ENV

      - uses: flipt-io/ffs-action@main
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          flipt-url: "https://bea7-81-105-194-215.ngrok-free.app"
