name: Deploy Preview

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-preview:
    name: Deploy Preview Environment
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.PREDICTABLE_BOT_APP_ID }}
          installation_id: ${{ secrets.PREDICTABLE_BOT_INSTALLATION_ID }}
          private_key: ${{ secrets.PREDICTABLE_BOT_PRIVATE_KEY_PEM }}

      - name: Deploy Preview
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            console.log(context.pull_request.head);
            const deployment = await github.rest.repos.createDeployment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
              description: "Your application has been deployed to a preview environment.\nFlipt has also been deployed and is tracking the [preview/deployment-abcdefg](https://github.com/predictab-le/config/tree/preview/deployment-abcdefg) branch.",
              transient_environment: true,
            });

            const status = await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: "success",
              target_url: "https://preview-predictd-abcdefg.predictab.le",
            });

            console.log(status);
 
